version: '3.9'
services:
  nestapp:
    container_name: store-service
    image: mikesivak/store-service:1.0.0
    build: .
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - DB_TYPE=${DATABASE_TYPE}
      - PG_USER=${DATABASE_USER}
      - PG_PASSWORD=${DATABASE_PASSWORD}
      - PG_DB=${DATABASE_NAME}
      - PG_PORT=${DATABASE_PORT}
      - PG_HOST=db
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
